/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YtConnectedRouteImport } from './routes/yt-connected'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TagManagerRouteImport } from './routes/tag-manager'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as ScriptRouteImport } from './routes/script'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreatorSettingsRouteImport } from './routes/creator-settings'
import { Route as CreatorLoginRouteImport } from './routes/creator-login'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsletterIndexRouteImport } from './routes/newsletter.index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as NewsletterConfirmRouteImport } from './routes/newsletter.confirm'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as DashboardConnectedRouteImport } from './routes/dashboard.connected'
import { Route as LayoutAdministratorIndexRouteImport } from './routes/_layout.administrator.index'
import { Route as ApiWebhooksMailgunRouteImport } from './routes/api/webhooks/mailgun'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'
import { Route as ApiPublicConfirmRouteImport } from './routes/api/public/confirm'
import { Route as LayoutAdministratorSubscribersRouteImport } from './routes/_layout.administrator.subscribers'
import { Route as LayoutAdministratorSponsorsRouteImport } from './routes/_layout.administrator.sponsors'
import { Route as LayoutAdministratorSettingsRouteImport } from './routes/_layout.administrator.settings'
import { Route as LayoutAdministratorMailingRouteImport } from './routes/_layout.administrator.mailing'
import { Route as LayoutAdministratorMailgunRouteImport } from './routes/_layout.administrator.mailgun'
import { Route as LayoutAdministratorLandingsRouteImport } from './routes/_layout.administrator.landings'
import { Route as LayoutAdministratorDashboardRouteImport } from './routes/_layout.administrator.dashboard'
import { Route as LayoutAdministratorAddProductRouteImport } from './routes/_layout.administrator.add-product'
import { Route as ApiPublicAdcomboOrderRouteImport } from './routes/api/public/adcombo.order'
import { Route as ApiAuthYoutubeCallbackRouteImport } from './routes/api/auth/youtube.callback'
import { Route as LayoutAdministratorMailingSystemRouteImport } from './routes/_layout.administrator.mailing.system'

const YtConnectedRoute = YtConnectedRouteImport.update({
  id: '/yt-connected',
  path: '/yt-connected',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TagManagerRoute = TagManagerRouteImport.update({
  id: '/tag-manager',
  path: '/tag-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptRoute = ScriptRouteImport.update({
  id: '/script',
  path: '/script',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSettingsRoute = CreatorSettingsRouteImport.update({
  id: '/creator-settings',
  path: '/creator-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorLoginRoute = CreatorLoginRouteImport.update({
  id: '/creator-login',
  path: '/creator-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterIndexRoute = NewsletterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsletterRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmRoute = NewsletterConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => NewsletterRoute,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardConnectedRoute = DashboardConnectedRouteImport.update({
  id: '/connected',
  path: '/connected',
  getParentRoute: () => DashboardRoute,
} as any)
const LayoutAdministratorIndexRoute =
  LayoutAdministratorIndexRouteImport.update({
    id: '/administrator/',
    path: '/administrator/',
    getParentRoute: () => LayoutRoute,
  } as any)
const ApiWebhooksMailgunRoute = ApiWebhooksMailgunRouteImport.update({
  id: '/api/webhooks/mailgun',
  path: '/api/webhooks/mailgun',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfirmRoute = ApiPublicConfirmRouteImport.update({
  id: '/api/public/confirm',
  path: '/api/public/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAdministratorSubscribersRoute =
  LayoutAdministratorSubscribersRouteImport.update({
    id: '/administrator/subscribers',
    path: '/administrator/subscribers',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdministratorSponsorsRoute =
  LayoutAdministratorSponsorsRouteImport.update({
    id: '/administrator/sponsors',
    path: '/administrator/sponsors',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdministratorSettingsRoute =
  LayoutAdministratorSettingsRouteImport.update({
    id: '/administrator/settings',
    path: '/administrator/settings',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdministratorMailingRoute =
  LayoutAdministratorMailingRouteImport.update({
    id: '/administrator/mailing',
    path: '/administrator/mailing',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdministratorMailgunRoute =
  LayoutAdministratorMailgunRouteImport.update({
    id: '/administrator/mailgun',
    path: '/administrator/mailgun',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdministratorLandingsRoute =
  LayoutAdministratorLandingsRouteImport.update({
    id: '/administrator/landings',
    path: '/administrator/landings',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdministratorDashboardRoute =
  LayoutAdministratorDashboardRouteImport.update({
    id: '/administrator/dashboard',
    path: '/administrator/dashboard',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdministratorAddProductRoute =
  LayoutAdministratorAddProductRouteImport.update({
    id: '/administrator/add-product',
    path: '/administrator/add-product',
    getParentRoute: () => LayoutRoute,
  } as any)
const ApiPublicAdcomboOrderRoute = ApiPublicAdcomboOrderRouteImport.update({
  id: '/api/public/adcombo/order',
  path: '/api/public/adcombo/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthYoutubeCallbackRoute = ApiAuthYoutubeCallbackRouteImport.update({
  id: '/api/auth/youtube/callback',
  path: '/api/auth/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAdministratorMailingSystemRoute =
  LayoutAdministratorMailingSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => LayoutAdministratorMailingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/calendar': typeof CalendarRoute
  '/competitors': typeof CompetitorsRoute
  '/creator-login': typeof CreatorLoginRoute
  '/creator-settings': typeof CreatorSettingsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/script': typeof ScriptRoute
  '/seo': typeof SeoRoute
  '/signup': typeof SignupRoute
  '/tag-manager': typeof TagManagerRoute
  '/upload': typeof UploadRoute
  '/yt-connected': typeof YtConnectedRoute
  '/dashboard/connected': typeof DashboardConnectedRoute
  '/l/$slug': typeof LSlugRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/p/$slug': typeof PSlugRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/administrator/add-product': typeof LayoutAdministratorAddProductRoute
  '/administrator/dashboard': typeof LayoutAdministratorDashboardRoute
  '/administrator/landings': typeof LayoutAdministratorLandingsRoute
  '/administrator/mailgun': typeof LayoutAdministratorMailgunRoute
  '/administrator/mailing': typeof LayoutAdministratorMailingRouteWithChildren
  '/administrator/settings': typeof LayoutAdministratorSettingsRoute
  '/administrator/sponsors': typeof LayoutAdministratorSponsorsRoute
  '/administrator/subscribers': typeof LayoutAdministratorSubscribersRoute
  '/api/public/confirm': typeof ApiPublicConfirmRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/webhooks/mailgun': typeof ApiWebhooksMailgunRoute
  '/administrator/': typeof LayoutAdministratorIndexRoute
  '/administrator/mailing/system': typeof LayoutAdministratorMailingSystemRoute
  '/api/auth/youtube/callback': typeof ApiAuthYoutubeCallbackRoute
  '/api/public/adcombo/order': typeof ApiPublicAdcomboOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/calendar': typeof CalendarRoute
  '/competitors': typeof CompetitorsRoute
  '/creator-login': typeof CreatorLoginRoute
  '/creator-settings': typeof CreatorSettingsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/script': typeof ScriptRoute
  '/seo': typeof SeoRoute
  '/signup': typeof SignupRoute
  '/tag-manager': typeof TagManagerRoute
  '/upload': typeof UploadRoute
  '/yt-connected': typeof YtConnectedRoute
  '/dashboard/connected': typeof DashboardConnectedRoute
  '/l/$slug': typeof LSlugRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/p/$slug': typeof PSlugRoute
  '/newsletter': typeof NewsletterIndexRoute
  '/administrator/add-product': typeof LayoutAdministratorAddProductRoute
  '/administrator/dashboard': typeof LayoutAdministratorDashboardRoute
  '/administrator/landings': typeof LayoutAdministratorLandingsRoute
  '/administrator/mailgun': typeof LayoutAdministratorMailgunRoute
  '/administrator/mailing': typeof LayoutAdministratorMailingRouteWithChildren
  '/administrator/settings': typeof LayoutAdministratorSettingsRoute
  '/administrator/sponsors': typeof LayoutAdministratorSponsorsRoute
  '/administrator/subscribers': typeof LayoutAdministratorSubscribersRoute
  '/api/public/confirm': typeof ApiPublicConfirmRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/webhooks/mailgun': typeof ApiWebhooksMailgunRoute
  '/administrator': typeof LayoutAdministratorIndexRoute
  '/administrator/mailing/system': typeof LayoutAdministratorMailingSystemRoute
  '/api/auth/youtube/callback': typeof ApiAuthYoutubeCallbackRoute
  '/api/public/adcombo/order': typeof ApiPublicAdcomboOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/blog': typeof BlogRoute
  '/calendar': typeof CalendarRoute
  '/competitors': typeof CompetitorsRoute
  '/creator-login': typeof CreatorLoginRoute
  '/creator-settings': typeof CreatorSettingsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/script': typeof ScriptRoute
  '/seo': typeof SeoRoute
  '/signup': typeof SignupRoute
  '/tag-manager': typeof TagManagerRoute
  '/upload': typeof UploadRoute
  '/yt-connected': typeof YtConnectedRoute
  '/dashboard/connected': typeof DashboardConnectedRoute
  '/l/$slug': typeof LSlugRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/p/$slug': typeof PSlugRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/_layout/administrator/add-product': typeof LayoutAdministratorAddProductRoute
  '/_layout/administrator/dashboard': typeof LayoutAdministratorDashboardRoute
  '/_layout/administrator/landings': typeof LayoutAdministratorLandingsRoute
  '/_layout/administrator/mailgun': typeof LayoutAdministratorMailgunRoute
  '/_layout/administrator/mailing': typeof LayoutAdministratorMailingRouteWithChildren
  '/_layout/administrator/settings': typeof LayoutAdministratorSettingsRoute
  '/_layout/administrator/sponsors': typeof LayoutAdministratorSponsorsRoute
  '/_layout/administrator/subscribers': typeof LayoutAdministratorSubscribersRoute
  '/api/public/confirm': typeof ApiPublicConfirmRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/webhooks/mailgun': typeof ApiWebhooksMailgunRoute
  '/_layout/administrator/': typeof LayoutAdministratorIndexRoute
  '/_layout/administrator/mailing/system': typeof LayoutAdministratorMailingSystemRoute
  '/api/auth/youtube/callback': typeof ApiAuthYoutubeCallbackRoute
  '/api/public/adcombo/order': typeof ApiPublicAdcomboOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/calendar'
    | '/competitors'
    | '/creator-login'
    | '/creator-settings'
    | '/dashboard'
    | '/login'
    | '/newsletter'
    | '/onboarding'
    | '/script'
    | '/seo'
    | '/signup'
    | '/tag-manager'
    | '/upload'
    | '/yt-connected'
    | '/dashboard/connected'
    | '/l/$slug'
    | '/newsletter/confirm'
    | '/p/$slug'
    | '/newsletter/'
    | '/administrator/add-product'
    | '/administrator/dashboard'
    | '/administrator/landings'
    | '/administrator/mailgun'
    | '/administrator/mailing'
    | '/administrator/settings'
    | '/administrator/sponsors'
    | '/administrator/subscribers'
    | '/api/public/confirm'
    | '/api/public/unsubscribe'
    | '/api/webhooks/mailgun'
    | '/administrator/'
    | '/administrator/mailing/system'
    | '/api/auth/youtube/callback'
    | '/api/public/adcombo/order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/calendar'
    | '/competitors'
    | '/creator-login'
    | '/creator-settings'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/script'
    | '/seo'
    | '/signup'
    | '/tag-manager'
    | '/upload'
    | '/yt-connected'
    | '/dashboard/connected'
    | '/l/$slug'
    | '/newsletter/confirm'
    | '/p/$slug'
    | '/newsletter'
    | '/administrator/add-product'
    | '/administrator/dashboard'
    | '/administrator/landings'
    | '/administrator/mailgun'
    | '/administrator/mailing'
    | '/administrator/settings'
    | '/administrator/sponsors'
    | '/administrator/subscribers'
    | '/api/public/confirm'
    | '/api/public/unsubscribe'
    | '/api/webhooks/mailgun'
    | '/administrator'
    | '/administrator/mailing/system'
    | '/api/auth/youtube/callback'
    | '/api/public/adcombo/order'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/blog'
    | '/calendar'
    | '/competitors'
    | '/creator-login'
    | '/creator-settings'
    | '/dashboard'
    | '/login'
    | '/newsletter'
    | '/onboarding'
    | '/script'
    | '/seo'
    | '/signup'
    | '/tag-manager'
    | '/upload'
    | '/yt-connected'
    | '/dashboard/connected'
    | '/l/$slug'
    | '/newsletter/confirm'
    | '/p/$slug'
    | '/newsletter/'
    | '/_layout/administrator/add-product'
    | '/_layout/administrator/dashboard'
    | '/_layout/administrator/landings'
    | '/_layout/administrator/mailgun'
    | '/_layout/administrator/mailing'
    | '/_layout/administrator/settings'
    | '/_layout/administrator/sponsors'
    | '/_layout/administrator/subscribers'
    | '/api/public/confirm'
    | '/api/public/unsubscribe'
    | '/api/webhooks/mailgun'
    | '/_layout/administrator/'
    | '/_layout/administrator/mailing/system'
    | '/api/auth/youtube/callback'
    | '/api/public/adcombo/order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  BlogRoute: typeof BlogRoute
  CalendarRoute: typeof CalendarRoute
  CompetitorsRoute: typeof CompetitorsRoute
  CreatorLoginRoute: typeof CreatorLoginRoute
  CreatorSettingsRoute: typeof CreatorSettingsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ScriptRoute: typeof ScriptRoute
  SeoRoute: typeof SeoRoute
  SignupRoute: typeof SignupRoute
  TagManagerRoute: typeof TagManagerRoute
  UploadRoute: typeof UploadRoute
  YtConnectedRoute: typeof YtConnectedRoute
  LSlugRoute: typeof LSlugRoute
  PSlugRoute: typeof PSlugRoute
  ApiPublicConfirmRoute: typeof ApiPublicConfirmRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
  ApiWebhooksMailgunRoute: typeof ApiWebhooksMailgunRoute
  ApiAuthYoutubeCallbackRoute: typeof ApiAuthYoutubeCallbackRoute
  ApiPublicAdcomboOrderRoute: typeof ApiPublicAdcomboOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yt-connected': {
      id: '/yt-connected'
      path: '/yt-connected'
      fullPath: '/yt-connected'
      preLoaderRoute: typeof YtConnectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag-manager': {
      id: '/tag-manager'
      path: '/tag-manager'
      fullPath: '/tag-manager'
      preLoaderRoute: typeof TagManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/script': {
      id: '/script'
      path: '/script'
      fullPath: '/script'
      preLoaderRoute: typeof ScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-settings': {
      id: '/creator-settings'
      path: '/creator-settings'
      fullPath: '/creator-settings'
      preLoaderRoute: typeof CreatorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-login': {
      id: '/creator-login'
      path: '/creator-login'
      fullPath: '/creator-login'
      preLoaderRoute: typeof CreatorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/': {
      id: '/newsletter/'
      path: '/'
      fullPath: '/newsletter/'
      preLoaderRoute: typeof NewsletterIndexRouteImport
      parentRoute: typeof NewsletterRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirm': {
      id: '/newsletter/confirm'
      path: '/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof NewsletterConfirmRouteImport
      parentRoute: typeof NewsletterRoute
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/connected': {
      id: '/dashboard/connected'
      path: '/connected'
      fullPath: '/dashboard/connected'
      preLoaderRoute: typeof DashboardConnectedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_layout/administrator/': {
      id: '/_layout/administrator/'
      path: '/administrator'
      fullPath: '/administrator/'
      preLoaderRoute: typeof LayoutAdministratorIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/webhooks/mailgun': {
      id: '/api/webhooks/mailgun'
      path: '/api/webhooks/mailgun'
      fullPath: '/api/webhooks/mailgun'
      preLoaderRoute: typeof ApiWebhooksMailgunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/confirm': {
      id: '/api/public/confirm'
      path: '/api/public/confirm'
      fullPath: '/api/public/confirm'
      preLoaderRoute: typeof ApiPublicConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/administrator/subscribers': {
      id: '/_layout/administrator/subscribers'
      path: '/administrator/subscribers'
      fullPath: '/administrator/subscribers'
      preLoaderRoute: typeof LayoutAdministratorSubscribersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/administrator/sponsors': {
      id: '/_layout/administrator/sponsors'
      path: '/administrator/sponsors'
      fullPath: '/administrator/sponsors'
      preLoaderRoute: typeof LayoutAdministratorSponsorsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/administrator/settings': {
      id: '/_layout/administrator/settings'
      path: '/administrator/settings'
      fullPath: '/administrator/settings'
      preLoaderRoute: typeof LayoutAdministratorSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/administrator/mailing': {
      id: '/_layout/administrator/mailing'
      path: '/administrator/mailing'
      fullPath: '/administrator/mailing'
      preLoaderRoute: typeof LayoutAdministratorMailingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/administrator/mailgun': {
      id: '/_layout/administrator/mailgun'
      path: '/administrator/mailgun'
      fullPath: '/administrator/mailgun'
      preLoaderRoute: typeof LayoutAdministratorMailgunRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/administrator/landings': {
      id: '/_layout/administrator/landings'
      path: '/administrator/landings'
      fullPath: '/administrator/landings'
      preLoaderRoute: typeof LayoutAdministratorLandingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/administrator/dashboard': {
      id: '/_layout/administrator/dashboard'
      path: '/administrator/dashboard'
      fullPath: '/administrator/dashboard'
      preLoaderRoute: typeof LayoutAdministratorDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/administrator/add-product': {
      id: '/_layout/administrator/add-product'
      path: '/administrator/add-product'
      fullPath: '/administrator/add-product'
      preLoaderRoute: typeof LayoutAdministratorAddProductRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/public/adcombo/order': {
      id: '/api/public/adcombo/order'
      path: '/api/public/adcombo/order'
      fullPath: '/api/public/adcombo/order'
      preLoaderRoute: typeof ApiPublicAdcomboOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/youtube/callback': {
      id: '/api/auth/youtube/callback'
      path: '/api/auth/youtube/callback'
      fullPath: '/api/auth/youtube/callback'
      preLoaderRoute: typeof ApiAuthYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/administrator/mailing/system': {
      id: '/_layout/administrator/mailing/system'
      path: '/system'
      fullPath: '/administrator/mailing/system'
      preLoaderRoute: typeof LayoutAdministratorMailingSystemRouteImport
      parentRoute: typeof LayoutAdministratorMailingRoute
    }
  }
}

interface LayoutAdministratorMailingRouteChildren {
  LayoutAdministratorMailingSystemRoute: typeof LayoutAdministratorMailingSystemRoute
}

const LayoutAdministratorMailingRouteChildren: LayoutAdministratorMailingRouteChildren =
  {
    LayoutAdministratorMailingSystemRoute:
      LayoutAdministratorMailingSystemRoute,
  }

const LayoutAdministratorMailingRouteWithChildren =
  LayoutAdministratorMailingRoute._addFileChildren(
    LayoutAdministratorMailingRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdministratorAddProductRoute: typeof LayoutAdministratorAddProductRoute
  LayoutAdministratorDashboardRoute: typeof LayoutAdministratorDashboardRoute
  LayoutAdministratorLandingsRoute: typeof LayoutAdministratorLandingsRoute
  LayoutAdministratorMailgunRoute: typeof LayoutAdministratorMailgunRoute
  LayoutAdministratorMailingRoute: typeof LayoutAdministratorMailingRouteWithChildren
  LayoutAdministratorSettingsRoute: typeof LayoutAdministratorSettingsRoute
  LayoutAdministratorSponsorsRoute: typeof LayoutAdministratorSponsorsRoute
  LayoutAdministratorSubscribersRoute: typeof LayoutAdministratorSubscribersRoute
  LayoutAdministratorIndexRoute: typeof LayoutAdministratorIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdministratorAddProductRoute: LayoutAdministratorAddProductRoute,
  LayoutAdministratorDashboardRoute: LayoutAdministratorDashboardRoute,
  LayoutAdministratorLandingsRoute: LayoutAdministratorLandingsRoute,
  LayoutAdministratorMailgunRoute: LayoutAdministratorMailgunRoute,
  LayoutAdministratorMailingRoute: LayoutAdministratorMailingRouteWithChildren,
  LayoutAdministratorSettingsRoute: LayoutAdministratorSettingsRoute,
  LayoutAdministratorSponsorsRoute: LayoutAdministratorSponsorsRoute,
  LayoutAdministratorSubscribersRoute: LayoutAdministratorSubscribersRoute,
  LayoutAdministratorIndexRoute: LayoutAdministratorIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface DashboardRouteChildren {
  DashboardConnectedRoute: typeof DashboardConnectedRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConnectedRoute: DashboardConnectedRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface NewsletterRouteChildren {
  NewsletterConfirmRoute: typeof NewsletterConfirmRoute
  NewsletterIndexRoute: typeof NewsletterIndexRoute
}

const NewsletterRouteChildren: NewsletterRouteChildren = {
  NewsletterConfirmRoute: NewsletterConfirmRoute,
  NewsletterIndexRoute: NewsletterIndexRoute,
}

const NewsletterRouteWithChildren = NewsletterRoute._addFileChildren(
  NewsletterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  BlogRoute: BlogRoute,
  CalendarRoute: CalendarRoute,
  CompetitorsRoute: CompetitorsRoute,
  CreatorLoginRoute: CreatorLoginRoute,
  CreatorSettingsRoute: CreatorSettingsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ScriptRoute: ScriptRoute,
  SeoRoute: SeoRoute,
  SignupRoute: SignupRoute,
  TagManagerRoute: TagManagerRoute,
  UploadRoute: UploadRoute,
  YtConnectedRoute: YtConnectedRoute,
  LSlugRoute: LSlugRoute,
  PSlugRoute: PSlugRoute,
  ApiPublicConfirmRoute: ApiPublicConfirmRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
  ApiWebhooksMailgunRoute: ApiWebhooksMailgunRoute,
  ApiAuthYoutubeCallbackRoute: ApiAuthYoutubeCallbackRoute,
  ApiPublicAdcomboOrderRoute: ApiPublicAdcomboOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
